name: Playwright Tests
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Determine Base Branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
          else
            echo "BASE_BRANCH=master" >> $GITHUB_ENV  # Change to match your repo's default branch
          fi

      - name: Fetch base branch
        run: |
          git fetch --all  # Fetch all branches to ensure comparison works
          git branch -r    # List remote branches to verify fetch worked

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Debug Git Diff
        run: |
          echo "Checking modified files..."
          git status
          echo "---------------------------"
          echo "Git log of last 2 commits:"
          git log --oneline -2
          echo "---------------------------"
          echo "Files changed in last commit:"
          git diff --name-only HEAD^ HEAD


      - name: Detect modified test files
        id: modified-tests
        run: |
          echo "Comparing changes against master"
          
          # Debugging Git behavior
          git status
          git log --oneline -2
          git diff --name-only origin/master HEAD

          echo "------------------------"
          echo "Files changed in last commit:"
          git diff --name-only HEAD^ HEAD -- '*.spec.ts'

          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.spec.ts' || true)

          if [[ -z "$MODIFIED_FILES" ]]; then
            echo "No modified test files detected."
            echo "run_tests=false" >> $GITHUB_ENV
          else
            echo "Modified test files detected: $MODIFIED_FILES"
            echo "run_tests=true" >> $GITHUB_ENV
            echo "$MODIFIED_FILES" > modified_tests.txt
          fi

      - name: Run modified Playwright tests
        if: env.run_tests == 'true'
        run: |
          if [[ -s modified_tests.txt ]]; then
            MODIFIED_TESTS=$(cat modified_tests.txt | tr '\n' ' ')
            echo "Executing modified tests: $MODIFIED_TESTS"
            npx playwright test $MODIFIED_TESTS --grep '@regression'
          else
            echo "No matching modified test files found in the push."
          fi

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
